- hosts: localhost

  tasks:
    - name: Check and reserve app domain/path
      command: 'yunohost app checkurl {{ domain }}{{ path }} -a {{ app_name }}'
      sudo: yes

    - include: tasks/sources.yml

    - name: Save is_public app setting
      command: 'yunohost app setting {{ app_name }} is_public -v {{ is_public }}'
      sudo: yes

    - include: tasks/config.yml

  handlers:
    - include: handlers/main.yml
