#!/bin/bash
set -e

# App name
app=anarchism

# Install ansible
sudo apt-get install -y -qq ansible

# Run ansible install playbook
ynh_ansible_operation install $app "domain=$1 path=$2 is_public=$3"
