#!/bin/bash
set -e

# App name
app=anarchism

# Install ansible
sudo apt-get install -y -qq ansible

# Run ansible install playbook
ansible-playbook \
    ansible/playbooks/install.yml \
    -i localhost, \
    -c local \
    -e "app_name=$app \
        domain=$1 \
        path=$2 \
        is_public=$3"
