#!/bin/bash
set -e

# App name
app=anarchism

# Install ansible
sudo apt-get install -y -qq ansible

# Run ansible remove playbook
ansible-playbook \
    ansible/playbooks/remove.yml \
    -i localhost, \
    -c local \
    -e "app_name=$app"
