- name: Put Nginx conf
  template:
    src: ../templates/nginx_anarchism.conf.j2
    dest: '/etc/nginx/conf.d/{{ domain }}.d/{{ app_name }}.conf'
  sudo: yes
  notify: Reload nginx

- name: Unprotect public uri
  command: 'yunohost app setting {{ app_name }} unprotected_uris -v /'
  when: is_public == "Yes"
  sudo: yes
